import type { Metadata } from "next"
import { Karla } from "next/font/google"
import "./painel.css"
import { AuthProvider } from "./provider/auth-provider"
import { ThemeProvider } from "@/app/painel/components/theme-provider"
import { SideBar } from "@/app/painel/components/sidebar"
import Header from "@/app/painel/components/header"
import PageWrapper from "@/app/painel/components/pagewrapper"

const karla = Karla({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-karla",
})

export const metadata: Metadata = {
  title: "Painel",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={karla.className}>
          <ThemeProvider themes={["dark", "custom", "light"]} attribute="class" enableSystem disableTransitionOnChange>
            <div className="min-h-screen flex">
              <SideBar></SideBar>
              <Header></Header>
              <PageWrapper>{children}</PageWrapper>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  )
}
